on: [push, pull_request]

name: Continuous Integration

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: mymindstorm/setup-emsdk@v11
        with: { version: "3.1.24" }
      - run: npm ci
      - name: build
        run: npm run build
      - name: test
        run: npm test
